/* eslint-disable @next/next/no-html-link-for-pages */
/* eslint-disable react/jsx-no-target-blank */
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Webiggle Digital Agency | We develop robust softwares</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <nav className='w-full max-w-4xl px-4 mx-auto sm:px-6 md:px-8 lg:px-16 pt-4 md:pt-8'>
        <div className='flex items-center justify-between -ml-2'>
          <a href="/" className='inline-flex items-center'>
            <Image 
              src="/logo.png"
              alt="Webiggle"
              width="42"
              height="42"
            />
          </a>
        </div>
      </nav>
      <div className="w-full max-w-4xl px-4 mx-auto sm:px-6 md:px-8 lg:px-16 pt-8 md:pt-12">
        <div className="pb-10">
          <h1 className="text-4xl md:text-5xl pb-4 md:pb-8 font-brand font-semibold">
            Welcome to Webiggle!
          </h1>

          <p className='font-sans text-xl sm:text-2xl text-gray-700 pb-4 md:pb-8'>
            We develop <span className='font-semibold text-cyan-700'>robust</span> web software, apps &amp; much more. We also contribute to <span className='font-semibold text-cyan-700'>OSS</span>.
          </p>
          <p className='font-sans text-lg text-gray-700 pb-2'>You can find our work at <a href="https://github.com/webiggle" target="_blank" className='font-semibold text-cyan-700'>Github</a>.</p>

          <p className='font-sans text-lg text-gray-700 pb-4 md:pb-8'>For any query &amp; information contact us by <a href="mailto:info@webiggle.com" target="_blank" className='font-semibold text-cyan-700'>Email</a>.</p>
        </div>
      </div>
    </>
  )
}
